DROP TABLE KAKAOTALK

CREATE TABLE KAKAOTALK(
           LOGIN_NO NUMBER(17),
           LOGIN_ID VARCHAR2(50),
           LOGIN_PW VARCHAR2(20),
           LOGIN_DATE DATE DEFAULT SYSDATE,
           RESIGN VARCHAR2(3) DEFAULT 'NO',
   
           CONSTRAINT KTT_LOGIN_PK PRIMARY KEY (LOGIN_NO),
           CONSTRAINT KTT_EMAIL_UK UNIQUE (LOGIN_ID),
           CONSTRAINT KTT_RESIGN_CK CHECK (RESIGN IN ('YES','NO'))
);

CREATE TABLE ACC_SKILL(
           SKILL_NO NUMBER(15),
           SKILL_NAME VARCHAR2(10),
           SKILL_TYPE VARCHAR2(10),
           SKILL_GRADE VARCHAR2(2),

           CONSTRAINT ACCSKL_NO_PK PRIMARY KEY (SKILL_NO)

)


CREATE TABLE FUNCT (
           FUNC_NO NUMBER(15),
           FUNC_NAME VARCHAR2(10), 
           FUNC_TYPE VARCHAR2(10),
           FUNC_GRADE VARCHAR2(2),
           FUNC_LEVEL NUMBER(2),

           CONSTRAINT FUNC_NO_PK PRIMARY KEY (FUNC_NO)
)

CREATE TABLE PET (
           PET_NO NUMBER(15),
           PET_TYPE VARCHAR2(10),
           PET_NAME VARCHAR2(20),
           PET_PROMO VARCHAR2(3) DEFAULT 'NO',
           PET_AWAKEN VARCHAR2(3) DEFAULT 'NO',
           PET_FUNCT NUMBER(15),

           CONSTRAINT PET_NO_PK PRIMARY KEY (PET_NO),
           CONSTRAINT PET_PROMO_CK CHECK (PET_PROMO ='YES' or PET_PROMO = 'NO'),
           CONSTRAINT PET_AWAKEN_CK CHECK (PET_AWAKEN = 'YES' or PET_AWAKEN = 'NO'),
           CONSTRAINT PET_FUNC_FK FOREIGN KEY (PET_FUNCT) REFERENCES FUNCT(FUNC_NO)
)


CREATE TABLE EQUIP (
           EQUIP_NO NUMBER(15),
           EQUIP_TYPE VARCHAR2(10),
           EQUIP_NAME VARCHAR2(10),
           EQUIP_GRADE VARCHAR2(2),
           EQUIP_LEVEL VARCHAR2(3),
           EQUIP_FUNCT NUMBER(15),

           CONSTRAINT EQ_NO_PK PRIMARY KEY (EQUIP_NO),
           CONSTRAINT EQ_FUNC_FK FOREIGN KEY (EQUIP_FUNCT) REFERENCES FUNCT(FUNC_NO)
)

ALTER TABLE EQUIP
ADD CONSTRAINT EQ_NO_CK CHECK(EQUIP_NO LIKE'3%'),



CREATE TABLE LOBBY (
           LOGIN_NO NUMBER(17),
           GAME_ID VARCHAR2(20) NOT NULL,
           GAME_LEVEL NUMBER(3) DEFAULT 1 NOT NULL,
           ACC_SKILL NUMBER(15) NOT NULL,
           SEL_CHAR1 NUMBER (15) NOT NULL,
           SEL_CHAR2 NUMBER (15), 
           SEL_CHAR3 NUMBER (15), 
           SEL_CHAR4 NUMBER (15), 
           SEL_CHAR5 NUMBER (15), 
           LOBBYIN DATE NOT NULL,
           LOBBYOUT DATE,
           LEADER_CHAR NUMBER (15) NOT NULL,
           PET_NO NUMBER (15), 

           CONSTRAINT LBY_LONINNO_PK PRIMARY KEY (LOGIN_NO),
           CONSTRAINT LBY_ACCSKILL_FK FOREIGN KEY (ACC_SKILL) REFERENCES ACC_SKILL(SKILL_NO),
           CONSTRAINT LBY_PETNO_FK FOREIGN KEY (PET_NO) REFERENCES PET(PET_NO)
);

CREATE TABLE SKILL (
           SKILL_NO NUMBER(15),
           SKILL_NAME VARCHAR2(20),
           SKILL_TYPE VARCHAR2(10),
           SKILL_GRADE VARCHAR2(2),
           
           CONSTRAINT SKL_NO_PK PRIMARY KEY (SKILL_NO)
)


CREATE TABLE CHARACTER (
           CHAR_NO NUMBER(15),
           CHAR_TYPE VARCHAR2(10),
           CHAR_NAME VARCHAR2(10),
           CHAR_OVERLEVEL VARCHAR2(3),
           CHAR_PROMO VARCHAR2(3),
           CHAR_AWAKEN VARCHAR2(3),
           SKILL1 NUMBER(15) NOT NULL,
           SKILL2 NUMBER(15) NOT NULL,
           SKILL3 NUMBER(15) NOT NULL,
           SKILL4 NUMBER(15),
          
           CONSTRAINT CHR_CHRNO_PK PRIMARY KEY (CHAR_NO),
           CONSTRAINT CHR_CHROL_CK CHECK (CHAR_OVERLEVEL = 'YES' or CHAR_OVERLEVEL = 'NO'),
           CONSTRAINT CHR_CHRPM_CK CHECK (CHAR_PROMO = 'YES' or CHAR_PROMO = 'NO'),
           CONSTRAINT CHR_CHRAK_CK CHECK (CHAR_AWAKEN = 'YES' or CHAR_AWAKEN = 'NO'),
           CONSTRAINT CHR_SKILL1_FK FOREIGN KEY (SKILL1) REFERENCES SKILL(SKILL_NO),
           CONSTRAINT CHR_SKILL2_FK FOREIGN KEY (SKILL2) REFERENCES SKILL(SKILL_NO),
           CONSTRAINT CHR_SKILL3_FK FOREIGN KEY (SKILL3) REFERENCES SKILL(SKILL_NO),
           CONSTRAINT CHR_SKILL4_FK FOREIGN KEY (SKILL4) REFERENCES SKILL(SKILL_NO)
)


CREATE TABLE OWN_CHAR (
           OWN_CHAR_NO NUMBER(15),
           OWN_CHAR_TEAM VARCHAR2(3) DEFAULT 'NO',
           OWN_CHAR_LEVEL VARCHAR2(2) DEFAULT 1 NOT NULL,
           OWN_CHAR_EQUIP1 NUMBER(15),
           OWN_CHAR_EQUIP2 NUMBER(15),
           OWN_CHAR_EQUIP3 NUMBER(15),
           OWN_CHAR_EQUIP4 NUMBER(15),
           OWN_CHAR_EQUIP5 NUMBER(15),
           OWN_CHAR_EQUIP6 NUMBER(15),
           OWN_CHAR_EQUIP7 NUMBER(15),
           OWN_CHAR_EQUIP8 NUMBER(15),

           CONSTRAINT OCHR_NO_PK PRIMARY KEY (OWN_CHAR_NO),
           CONSTRAINT OCHR_TEAM_CK CHECK (OWN_CHAR_TEAM IN ('YES','NO')),
           CONSTRAINT OCHR_EQ1_FK FOREIGN KEY (OWN_CHAR_EQUIP1) REFERENCES EQUIP(EQUIP_NO),
           CONSTRAINT OCHR_EQ2_FK FOREIGN KEY (OWN_CHAR_EQUIP2) REFERENCES EQUIP(EQUIP_NO),
           CONSTRAINT OCHR_EQ3_FK FOREIGN KEY (OWN_CHAR_EQUIP3) REFERENCES EQUIP(EQUIP_NO),
           CONSTRAINT OCHR_EQ4_FK FOREIGN KEY (OWN_CHAR_EQUIP4) REFERENCES EQUIP(EQUIP_NO),
           CONSTRAINT OCHR_EQ5_FK FOREIGN KEY (OWN_CHAR_EQUIP5) REFERENCES EQUIP(EQUIP_NO),
           CONSTRAINT OCHR_EQ6_FK FOREIGN KEY (OWN_CHAR_EQUIP6) REFERENCES EQUIP(EQUIP_NO),
           CONSTRAINT OCHR_EQ7_FK FOREIGN KEY (OWN_CHAR_EQUIP7) REFERENCES EQUIP(EQUIP_NO),
           CONSTRAINT OCHR_EQ8_FK FOREIGN KEY (OWN_CHAR_EQUIP8) REFERENCES EQUIP(EQUIP_NO)
)




insert into kakaotalk (LOGIN_NO, LOGIN_ID, LOGIN_PW)
values (8809246125534336, 'RYON81@GMAIL.COM', '123456789');

SELECT * FROM KAKAOTALK;


INSERT INTO ACC_SKILL (SKILL_NO, SKILL_NAME, SKILL_TYPE, SKILL_GRADE)
VALUES (100000000000010, '절제된 힘', 'ATTACK', 10);

SELECT * FROM ACC_SKILL;


INSERT INTO FUNCT (FUNC_NO, FUNC_NAME, FUNC_TYPE, FUNC_GRADE, FUNC_LEVEL)
VALUES (200000000000001,'펫의 응원','SUPPORT','D','1')
INSERT INTO FUNCT (FUNC_NO, FUNC_NAME, FUNC_TYPE, FUNC_GRADE, FUNC_LEVEL)
VALUES (210000000000001,'공격력','ATTACK','S','1')

SELECT * FROM FUNCT;

INSERT INTO PET (PET_NO, PET_TYPE, PET_NAME, PET_FUNCT)
VALUES (300000000000001, 'SUPPORT', '아기여우유우',200000000000001)

SELECT * FROM PET;


INSERT INTO EQUIP (EQUIP_NO, EQUIP_TYPE, EQUIP_NAME, EQUIP_GRADE,
           EQUIP_LEVEL, EQUIP_FUNCT)
VALUES (400000000000001, '세븐나이츠', '아일린의창','S','4',210000000000001)

SELECT * FROM EQUIP;


INSERT INTO SKILL (SKILL_NO, SKILL_NAME, SKILL_TYPE, SKILL_GRADE)
VALUES (510000000000002, '청천벽력', '사용','S')

VALUES (500000000000001, '포디나의 분노', '지속','S')
SELECT * FROM SKILL;
    


INSERT INTO CHARACTER (CHAR_NO, CHAR_TYPE, CHAR_NAME, CHAR_OVERLEVEL, CHAR_PROMO, CHAR_AWAKEN, SKILL1, SKILL2, SKILL3, SKILL4)
VALUES (600000000000001, '세븐나이츠','아일린', 'NO','NO','NO',500000000000001, 510000000000001,510000000000002,NULL)

SELECT * FROM CHARACTER;


INSERT INTO OWN_CHAR 
VALUES (600000000000001,'NO',1,400000000000001,400000000000001,NULL,NULL,NULL,NULL,NULL,NULL)

SELECT * FROM OWN_CHAR;

DELETE FROM OWN_CHAR;

CREATE TABLE OWN_CHAR (
           OWN_CHAR_NO NUMBER(15),
           OWN_CHAR_TEAM VARCHAR2(3) DEFAULT 'NO',
           OWN_CHAR_LEVEL VARCHAR2(2) DEFAULT 1 NOT NULL,
           OWN_CHAR_EQUIP1 NUMBER(15),
           OWN_CHAR_EQUIP2 NUMBER(15),
           OWN_CHAR_EQUIP3 NUMBER(15),
           OWN_CHAR_EQUIP4 NUMBER(15),
           OWN_CHAR_EQUIP5 NUMBER(15),
           OWN_CHAR_EQUIP6 NUMBER(15),
           OWN_CHAR_EQUIP7 NUMBER(15),
           OWN_CHAR_EQUIP8 NUMBER(15),

           CONSTRAINT OCHR_NO_PK PRIMARY KEY (OWN_CHAR_NO),
           CONSTRAINT OCHR_TEAM_CK CHECK (OWN_CHAR_TEAM IN ('YES','NO')),
           CONSTRAINT OCHR_EQ1_FK FOREIGN KEY (OWN_CHAR_EQUIP1) REFERENCES EQUIP(EQUIP_NO),
           CONSTRAINT OCHR_EQ2_FK FOREIGN KEY (OWN_CHAR_EQUIP2) REFERENCES EQUIP(EQUIP_NO),
           CONSTRAINT OCHR_EQ3_FK FOREIGN KEY (OWN_CHAR_EQUIP3) REFERENCES EQUIP(EQUIP_NO),
           CONSTRAINT OCHR_EQ4_FK FOREIGN KEY (OWN_CHAR_EQUIP4) REFERENCES EQUIP(EQUIP_NO),
           CONSTRAINT OCHR_EQ5_FK FOREIGN KEY (OWN_CHAR_EQUIP5) REFERENCES EQUIP(EQUIP_NO),
           CONSTRAINT OCHR_EQ6_FK FOREIGN KEY (OWN_CHAR_EQUIP6) REFERENCES EQUIP(EQUIP_NO),
           CONSTRAINT OCHR_EQ7_FK FOREIGN KEY (OWN_CHAR_EQUIP7) REFERENCES EQUIP(EQUIP_NO),
           CONSTRAINT OCHR_EQ8_FK FOREIGN KEY (OWN_CHAR_EQUIP8) REFERENCES EQUIP(EQUIP_NO)
)


ALTER TABLE LOBBY
ADD CONSTRAINT LNY_SELCHAR5_FK FOREIGN KEY (SEL_CHAR5) REFERENCES OWN_CHAR(OWN_CHAR_NO)
          





INSERT INTO LOBBY
VALUES (8809246125534336, '다프낸', 62, 100000000000010, 600000000000001,NULL,NULL,NULL,NULL,SYSDATE,NULL,600000000000001,300000000000001)
SELECT * FROM LOBBY;           
           
           
           LOGIN_NO NUMBER(17),
           GAME_ID VARCHAR2(20) NOT NULL,
           GAME_LEVEL NUMBER(3) DEFAULT 1 NOT NULL,
           ACC_SKILL NUMBER(15) NOT NULL,
           SEL_CHAR1 NUMBER (15) NOT NULL,
           SEL_CHAR2 NUMBER (15), 
           SEL_CHAR3 NUMBER (15), 
           SEL_CHAR4 NUMBER (15), 
           SEL_CHAR5 NUMBER (15), 
           LOBBYIN DATE NOT NULL,
           LOBBYOUT DATE,
           LEADER_CHAR NUMBER (15) NOT NULL,
           PET_NO NUMBER (15), 

           CONSTRAINT LBY_LONINNO_PK PRIMARY KEY (LOGIN_NO),
           CONSTRAINT LBY_ACCSKILL_FK FOREIGN KEY (ACC_SKILL) REFERENCES ACC_SKILL(SKILL_NO),
           CONSTRAINT LBY_PETNO_FK FOREIGN KEY (PET_NO) REFERENCES PET(PET_NO)