CREATE OR REPLACE PROCEDURE SEL_EMPNAME
(      VENAME IN EMP.ENAME%TYPE,
       VJOB OUT EMP.JOB%TYPE 
)
IS
BEGIN
     SELECT JOB INTO VJOB
     FROM EMP
     WHERE ENAME=VENAME;
END;
/


VARIABLE VAR_JOB VARCHAR2(9);

EXECUTE SEL_EMPNAME('SCOTT', :VAR_JOB);

PRINT VAR_ENAME;

SELECT * FROM EMP;
